---

- hosts: localhost
  tasks:
  - include_role:
      name: alanbchristie.pysimple
    vars:
      ingress_host: ''
      use_persistent_volume: yes
      volume_class: im-cinder-delete
      psp: im-core-unrestricted
