---

- name: Get information about the cluster
  set_fact:
    api_groups: "{{ lookup('k8s', cluster_info='api_groups') }}"

- name: Volume claim ({{ volume_class }})
  k8s:
    state: "{{ state }}"
    definition: "{{ lookup('template', 'pvc.yml.j2') }}"
  when: use_persistent_volume|bool

- name: Deploy roles and bindings
  k8s:
    state: "{{ state }}"
    definition: "{{ lookup('template', '{{ item }}.yml.j2') }}"
  when: psp|string|length > 0
  loop:
  - role
  - role-binding-default

- name: Set OpenShift fact
  set_fact:
    is_openshift: "{{ True if 'route.openshift.io' in api_groups else False }}"

- name: Deploy
  k8s:
    state: "{{ state }}"
    definition: "{{ lookup('template', '{{ item }}.yml.j2') }}"
  loop:
  - deployment
  - service

# Route or Ingress?

- name: Deploy Route
  k8s:
    state: "{{ state }}"
    definition: "{{ lookup('template', 'route.yml.j2') }}"
  when:
  - ingress_host|string|length > 0
  - is_openshift|bool

- name: Deploy Ingres
  k8s:
    state: "{{ state }}"
    definition: "{{ lookup('template', 'ingress.yml.j2') }}"
  when:
  - ingress_host|string|length > 0
  - not is_openshift|bool
