---

- name: Get information about the cluster
  set_fact:
    api_groups: "{{ lookup('k8s', cluster_info='api_groups') }}"

- name: Volume claim ({{ volume_class }})
  k8s:
    state: "{{ state }}"
    definition: "{{ lookup('template', '{{ item }}.yml.j2') }}"
  when: use_persistent_volume|bool
  loop:
  - name: pvc

- name: Deploy roles and bindings
  k8s:
    state: "{{ state }}"
    definition: "{{ lookup('template', '{{ item }}.yml.j2') }}"
  when: psp|string|length > 0
  loop:
  - name: role
  - name: role-binding-default

- name: Set objects state={{ state }}
  k8s:
    state: "{{ state }}"
    definition: "{{ lookup('template', '{{ item.name }}.yml.j2') }}"
  when: item.api_exists|default(True)
  loop:
  - name: deployment
  - name: service
  - name: route
    api_exists: "{{ True if 'route.openshift.io' in api_groups else False }}"
  - name: ingress
    api_exists: "{{ True if 'networking.k8s.io' in api_groups else False }}"
